shared:
  send-responsible-jobs:
    type: job_roles
    criteria:
      job_roles:
        - send_responsible
  ect-suitable-jobs:
    type: job_roles
    criteria:
      job_roles:
        - ect_suitable
  education-support-jobs:
    type: job_roles
    criteria:
      job_roles:
        - education_support
  leadership-jobs:
    type: job_roles
    criteria:
      job_roles:
        - leadership
  sendco-jobs:
    type: job_roles
    criteria:
      job_roles:
        - sendco
  teacher-jobs:
    type: job_roles
    criteria:
      job_roles:
        - teacher
  teaching-assistant-jobs:
    type: job_roles
    criteria:
      job_roles:
        - teaching_assistant
